//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JGS.BusinessLogicEngine.TimeOutWrapper {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TimeOutInfo", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class TimeOutInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GeographyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BCNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SerialNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PartNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WorkCenterIdField;
        
        private bool WarrantyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WoTimeLoggedInHoursField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NotesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResultCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<JGS.BusinessLogicEngine.TimeOutWrapper.InfoCodes> InfoCodeListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<JGS.BusinessLogicEngine.TimeOutWrapper.FlexFields> FlexFieldListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<JGS.BusinessLogicEngine.TimeOutWrapper.FlexFields> TimeOutFlexFieldListField;
        
        private JGS.BusinessLogicEngine.TimeOutWrapper.OperationTypes TimeOutTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClientNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContractNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string userNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string userPassField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OverRidePassField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModifyWarrantyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CallSourceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string APIUsage_LocationNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string APIUsage_ClientNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Geography {
            get {
                return this.GeographyField;
            }
            set {
                if ((object.ReferenceEquals(this.GeographyField, value) != true)) {
                    this.GeographyField = value;
                    this.RaisePropertyChanged("Geography");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string BCN {
            get {
                return this.BCNField;
            }
            set {
                if ((object.ReferenceEquals(this.BCNField, value) != true)) {
                    this.BCNField = value;
                    this.RaisePropertyChanged("BCN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string SerialNumber {
            get {
                return this.SerialNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.SerialNumberField, value) != true)) {
                    this.SerialNumberField = value;
                    this.RaisePropertyChanged("SerialNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string PartNumber {
            get {
                return this.PartNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PartNumberField, value) != true)) {
                    this.PartNumberField = value;
                    this.RaisePropertyChanged("PartNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string WorkCenterId {
            get {
                return this.WorkCenterIdField;
            }
            set {
                if ((object.ReferenceEquals(this.WorkCenterIdField, value) != true)) {
                    this.WorkCenterIdField = value;
                    this.RaisePropertyChanged("WorkCenterId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public bool Warranty {
            get {
                return this.WarrantyField;
            }
            set {
                if ((this.WarrantyField.Equals(value) != true)) {
                    this.WarrantyField = value;
                    this.RaisePropertyChanged("Warranty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string WoTimeLoggedInHours {
            get {
                return this.WoTimeLoggedInHoursField;
            }
            set {
                if ((object.ReferenceEquals(this.WoTimeLoggedInHoursField, value) != true)) {
                    this.WoTimeLoggedInHoursField = value;
                    this.RaisePropertyChanged("WoTimeLoggedInHours");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Notes {
            get {
                return this.NotesField;
            }
            set {
                if ((object.ReferenceEquals(this.NotesField, value) != true)) {
                    this.NotesField = value;
                    this.RaisePropertyChanged("Notes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string ResultCode {
            get {
                return this.ResultCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultCodeField, value) != true)) {
                    this.ResultCodeField = value;
                    this.RaisePropertyChanged("ResultCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public System.Collections.Generic.List<JGS.BusinessLogicEngine.TimeOutWrapper.InfoCodes> InfoCodeList {
            get {
                return this.InfoCodeListField;
            }
            set {
                if ((object.ReferenceEquals(this.InfoCodeListField, value) != true)) {
                    this.InfoCodeListField = value;
                    this.RaisePropertyChanged("InfoCodeList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public System.Collections.Generic.List<JGS.BusinessLogicEngine.TimeOutWrapper.FlexFields> FlexFieldList {
            get {
                return this.FlexFieldListField;
            }
            set {
                if ((object.ReferenceEquals(this.FlexFieldListField, value) != true)) {
                    this.FlexFieldListField = value;
                    this.RaisePropertyChanged("FlexFieldList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public System.Collections.Generic.List<JGS.BusinessLogicEngine.TimeOutWrapper.FlexFields> TimeOutFlexFieldList {
            get {
                return this.TimeOutFlexFieldListField;
            }
            set {
                if ((object.ReferenceEquals(this.TimeOutFlexFieldListField, value) != true)) {
                    this.TimeOutFlexFieldListField = value;
                    this.RaisePropertyChanged("TimeOutFlexFieldList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public JGS.BusinessLogicEngine.TimeOutWrapper.OperationTypes TimeOutType {
            get {
                return this.TimeOutTypeField;
            }
            set {
                if ((this.TimeOutTypeField.Equals(value) != true)) {
                    this.TimeOutTypeField = value;
                    this.RaisePropertyChanged("TimeOutType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string ClientName {
            get {
                return this.ClientNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientNameField, value) != true)) {
                    this.ClientNameField = value;
                    this.RaisePropertyChanged("ClientName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string ContractName {
            get {
                return this.ContractNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ContractNameField, value) != true)) {
                    this.ContractNameField = value;
                    this.RaisePropertyChanged("ContractName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string userName {
            get {
                return this.userNameField;
            }
            set {
                if ((object.ReferenceEquals(this.userNameField, value) != true)) {
                    this.userNameField = value;
                    this.RaisePropertyChanged("userName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string userPass {
            get {
                return this.userPassField;
            }
            set {
                if ((object.ReferenceEquals(this.userPassField, value) != true)) {
                    this.userPassField = value;
                    this.RaisePropertyChanged("userPass");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string OverRidePass {
            get {
                return this.OverRidePassField;
            }
            set {
                if ((object.ReferenceEquals(this.OverRidePassField, value) != true)) {
                    this.OverRidePassField = value;
                    this.RaisePropertyChanged("OverRidePass");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public string ModifyWarranty {
            get {
                return this.ModifyWarrantyField;
            }
            set {
                if ((object.ReferenceEquals(this.ModifyWarrantyField, value) != true)) {
                    this.ModifyWarrantyField = value;
                    this.RaisePropertyChanged("ModifyWarranty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=19)]
        public string IP {
            get {
                return this.IPField;
            }
            set {
                if ((object.ReferenceEquals(this.IPField, value) != true)) {
                    this.IPField = value;
                    this.RaisePropertyChanged("IP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=20)]
        public string CallSource {
            get {
                return this.CallSourceField;
            }
            set {
                if ((object.ReferenceEquals(this.CallSourceField, value) != true)) {
                    this.CallSourceField = value;
                    this.RaisePropertyChanged("CallSource");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=21)]
        public string APIUsage_LocationName {
            get {
                return this.APIUsage_LocationNameField;
            }
            set {
                if ((object.ReferenceEquals(this.APIUsage_LocationNameField, value) != true)) {
                    this.APIUsage_LocationNameField = value;
                    this.RaisePropertyChanged("APIUsage_LocationName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=22)]
        public string APIUsage_ClientName {
            get {
                return this.APIUsage_ClientNameField;
            }
            set {
                if ((object.ReferenceEquals(this.APIUsage_ClientNameField, value) != true)) {
                    this.APIUsage_ClientNameField = value;
                    this.RaisePropertyChanged("APIUsage_ClientName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfoCodes", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class InfoCodes : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InfoCodeField;
        
        private JGS.BusinessLogicEngine.TimeOutWrapper.CodeTypes CodeTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string InfoCode {
            get {
                return this.InfoCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.InfoCodeField, value) != true)) {
                    this.InfoCodeField = value;
                    this.RaisePropertyChanged("InfoCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public JGS.BusinessLogicEngine.TimeOutWrapper.CodeTypes CodeType {
            get {
                return this.CodeTypeField;
            }
            set {
                if ((this.CodeTypeField.Equals(value) != true)) {
                    this.CodeTypeField = value;
                    this.RaisePropertyChanged("CodeType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string CodeName {
            get {
                return this.CodeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeNameField, value) != true)) {
                    this.CodeNameField = value;
                    this.RaisePropertyChanged("CodeName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FlexFields", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class FlexFields : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperationTypes", Namespace="http://tempuri.org/")]
    public enum OperationTypes : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ProcessImmediate = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        QueueForDelay = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        QueueForImmediate = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UpdateQueueDelay = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DeleteQueueDelay = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ReleaseQueueDelay = 5,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CodeTypes", Namespace="http://tempuri.org/")]
    public enum CodeTypes : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Symptom = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Diagnostic = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Repair = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Fail = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TimeOutWrapper.TimeOutWrapperSoap")]
    public interface TimeOutWrapperSoap {
        
        // CODEGEN: Generating message contract since element name TimeOutInfo from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PerformTimeOut", ReplyAction="*")]
        JGS.BusinessLogicEngine.TimeOutWrapper.PerformTimeOutResponse PerformTimeOut(JGS.BusinessLogicEngine.TimeOutWrapper.PerformTimeOutRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PerformTimeOutRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PerformTimeOut", Namespace="http://tempuri.org/", Order=0)]
        public JGS.BusinessLogicEngine.TimeOutWrapper.PerformTimeOutRequestBody Body;
        
        public PerformTimeOutRequest() {
        }
        
        public PerformTimeOutRequest(JGS.BusinessLogicEngine.TimeOutWrapper.PerformTimeOutRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PerformTimeOutRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public JGS.BusinessLogicEngine.TimeOutWrapper.TimeOutInfo TimeOutInfo;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public bool JustReturnXMLString;
        
        public PerformTimeOutRequestBody() {
        }
        
        public PerformTimeOutRequestBody(JGS.BusinessLogicEngine.TimeOutWrapper.TimeOutInfo TimeOutInfo, bool JustReturnXMLString) {
            this.TimeOutInfo = TimeOutInfo;
            this.JustReturnXMLString = JustReturnXMLString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PerformTimeOutResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PerformTimeOutResponse", Namespace="http://tempuri.org/", Order=0)]
        public JGS.BusinessLogicEngine.TimeOutWrapper.PerformTimeOutResponseBody Body;
        
        public PerformTimeOutResponse() {
        }
        
        public PerformTimeOutResponse(JGS.BusinessLogicEngine.TimeOutWrapper.PerformTimeOutResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PerformTimeOutResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PerformTimeOutResult;
        
        public PerformTimeOutResponseBody() {
        }
        
        public PerformTimeOutResponseBody(string PerformTimeOutResult) {
            this.PerformTimeOutResult = PerformTimeOutResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TimeOutWrapperSoapChannel : JGS.BusinessLogicEngine.TimeOutWrapper.TimeOutWrapperSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TimeOutWrapperSoapClient : System.ServiceModel.ClientBase<JGS.BusinessLogicEngine.TimeOutWrapper.TimeOutWrapperSoap>, JGS.BusinessLogicEngine.TimeOutWrapper.TimeOutWrapperSoap {
        
        public TimeOutWrapperSoapClient() {
        }
        
        public TimeOutWrapperSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TimeOutWrapperSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TimeOutWrapperSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TimeOutWrapperSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        JGS.BusinessLogicEngine.TimeOutWrapper.PerformTimeOutResponse JGS.BusinessLogicEngine.TimeOutWrapper.TimeOutWrapperSoap.PerformTimeOut(JGS.BusinessLogicEngine.TimeOutWrapper.PerformTimeOutRequest request) {
            return base.Channel.PerformTimeOut(request);
        }
        
        public string PerformTimeOut(JGS.BusinessLogicEngine.TimeOutWrapper.TimeOutInfo TimeOutInfo, bool JustReturnXMLString) {
            JGS.BusinessLogicEngine.TimeOutWrapper.PerformTimeOutRequest inValue = new JGS.BusinessLogicEngine.TimeOutWrapper.PerformTimeOutRequest();
            inValue.Body = new JGS.BusinessLogicEngine.TimeOutWrapper.PerformTimeOutRequestBody();
            inValue.Body.TimeOutInfo = TimeOutInfo;
            inValue.Body.JustReturnXMLString = JustReturnXMLString;
            JGS.BusinessLogicEngine.TimeOutWrapper.PerformTimeOutResponse retVal = ((JGS.BusinessLogicEngine.TimeOutWrapper.TimeOutWrapperSoap)(this)).PerformTimeOut(inValue);
            return retVal.Body.PerformTimeOutResult;
        }
    }
}
