//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JGS.BusinessLogicEngine.ChangePartWrapper {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChangePartInfo", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ChangePartInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SesCustomerIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RequestIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BCNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NewSerialNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NewPartNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NewRevisionLevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NewFixedAssetTagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NotesField;
        
        private bool MustBeOnHoldField;
        
        private bool ReleaseIfHoldField;
        
        private bool MustBeTimedInField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TimedInWorkCenterNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<JGS.BusinessLogicEngine.ChangePartWrapper.FlexFields> FlexFieldListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string userNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CallSourceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string APIUsage_LocationNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string APIUsage_ClientNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SesCustomerID {
            get {
                return this.SesCustomerIDField;
            }
            set {
                if ((object.ReferenceEquals(this.SesCustomerIDField, value) != true)) {
                    this.SesCustomerIDField = value;
                    this.RaisePropertyChanged("SesCustomerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string RequestId {
            get {
                return this.RequestIdField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestIdField, value) != true)) {
                    this.RequestIdField = value;
                    this.RaisePropertyChanged("RequestId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string BCN {
            get {
                return this.BCNField;
            }
            set {
                if ((object.ReferenceEquals(this.BCNField, value) != true)) {
                    this.BCNField = value;
                    this.RaisePropertyChanged("BCN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string NewSerialNo {
            get {
                return this.NewSerialNoField;
            }
            set {
                if ((object.ReferenceEquals(this.NewSerialNoField, value) != true)) {
                    this.NewSerialNoField = value;
                    this.RaisePropertyChanged("NewSerialNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string NewPartNo {
            get {
                return this.NewPartNoField;
            }
            set {
                if ((object.ReferenceEquals(this.NewPartNoField, value) != true)) {
                    this.NewPartNoField = value;
                    this.RaisePropertyChanged("NewPartNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string NewRevisionLevel {
            get {
                return this.NewRevisionLevelField;
            }
            set {
                if ((object.ReferenceEquals(this.NewRevisionLevelField, value) != true)) {
                    this.NewRevisionLevelField = value;
                    this.RaisePropertyChanged("NewRevisionLevel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string NewFixedAssetTag {
            get {
                return this.NewFixedAssetTagField;
            }
            set {
                if ((object.ReferenceEquals(this.NewFixedAssetTagField, value) != true)) {
                    this.NewFixedAssetTagField = value;
                    this.RaisePropertyChanged("NewFixedAssetTag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Notes {
            get {
                return this.NotesField;
            }
            set {
                if ((object.ReferenceEquals(this.NotesField, value) != true)) {
                    this.NotesField = value;
                    this.RaisePropertyChanged("Notes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public bool MustBeOnHold {
            get {
                return this.MustBeOnHoldField;
            }
            set {
                if ((this.MustBeOnHoldField.Equals(value) != true)) {
                    this.MustBeOnHoldField = value;
                    this.RaisePropertyChanged("MustBeOnHold");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public bool ReleaseIfHold {
            get {
                return this.ReleaseIfHoldField;
            }
            set {
                if ((this.ReleaseIfHoldField.Equals(value) != true)) {
                    this.ReleaseIfHoldField = value;
                    this.RaisePropertyChanged("ReleaseIfHold");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public bool MustBeTimedIn {
            get {
                return this.MustBeTimedInField;
            }
            set {
                if ((this.MustBeTimedInField.Equals(value) != true)) {
                    this.MustBeTimedInField = value;
                    this.RaisePropertyChanged("MustBeTimedIn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string TimedInWorkCenterName {
            get {
                return this.TimedInWorkCenterNameField;
            }
            set {
                if ((object.ReferenceEquals(this.TimedInWorkCenterNameField, value) != true)) {
                    this.TimedInWorkCenterNameField = value;
                    this.RaisePropertyChanged("TimedInWorkCenterName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public System.Collections.Generic.List<JGS.BusinessLogicEngine.ChangePartWrapper.FlexFields> FlexFieldList {
            get {
                return this.FlexFieldListField;
            }
            set {
                if ((object.ReferenceEquals(this.FlexFieldListField, value) != true)) {
                    this.FlexFieldListField = value;
                    this.RaisePropertyChanged("FlexFieldList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string userName {
            get {
                return this.userNameField;
            }
            set {
                if ((object.ReferenceEquals(this.userNameField, value) != true)) {
                    this.userNameField = value;
                    this.RaisePropertyChanged("userName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string IP {
            get {
                return this.IPField;
            }
            set {
                if ((object.ReferenceEquals(this.IPField, value) != true)) {
                    this.IPField = value;
                    this.RaisePropertyChanged("IP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string CallSource {
            get {
                return this.CallSourceField;
            }
            set {
                if ((object.ReferenceEquals(this.CallSourceField, value) != true)) {
                    this.CallSourceField = value;
                    this.RaisePropertyChanged("CallSource");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string APIUsage_LocationName {
            get {
                return this.APIUsage_LocationNameField;
            }
            set {
                if ((object.ReferenceEquals(this.APIUsage_LocationNameField, value) != true)) {
                    this.APIUsage_LocationNameField = value;
                    this.RaisePropertyChanged("APIUsage_LocationName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public string APIUsage_ClientName {
            get {
                return this.APIUsage_ClientNameField;
            }
            set {
                if ((object.ReferenceEquals(this.APIUsage_ClientNameField, value) != true)) {
                    this.APIUsage_ClientNameField = value;
                    this.RaisePropertyChanged("APIUsage_ClientName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FlexFields", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class FlexFields : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ChangePartWrapper.ChangePartWrapperSoap")]
    public interface ChangePartWrapperSoap {
        
        // CODEGEN: Generating message contract since element name ChangePartInfo from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PerformChangePart", ReplyAction="*")]
        JGS.BusinessLogicEngine.ChangePartWrapper.PerformChangePartResponse PerformChangePart(JGS.BusinessLogicEngine.ChangePartWrapper.PerformChangePartRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PerformChangePartRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PerformChangePart", Namespace="http://tempuri.org/", Order=0)]
        public JGS.BusinessLogicEngine.ChangePartWrapper.PerformChangePartRequestBody Body;
        
        public PerformChangePartRequest() {
        }
        
        public PerformChangePartRequest(JGS.BusinessLogicEngine.ChangePartWrapper.PerformChangePartRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PerformChangePartRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public JGS.BusinessLogicEngine.ChangePartWrapper.ChangePartInfo ChangePartInfo;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public bool JustReturnXMLString;
        
        public PerformChangePartRequestBody() {
        }
        
        public PerformChangePartRequestBody(JGS.BusinessLogicEngine.ChangePartWrapper.ChangePartInfo ChangePartInfo, bool JustReturnXMLString) {
            this.ChangePartInfo = ChangePartInfo;
            this.JustReturnXMLString = JustReturnXMLString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PerformChangePartResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PerformChangePartResponse", Namespace="http://tempuri.org/", Order=0)]
        public JGS.BusinessLogicEngine.ChangePartWrapper.PerformChangePartResponseBody Body;
        
        public PerformChangePartResponse() {
        }
        
        public PerformChangePartResponse(JGS.BusinessLogicEngine.ChangePartWrapper.PerformChangePartResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PerformChangePartResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PerformChangePartResult;
        
        public PerformChangePartResponseBody() {
        }
        
        public PerformChangePartResponseBody(string PerformChangePartResult) {
            this.PerformChangePartResult = PerformChangePartResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ChangePartWrapperSoapChannel : JGS.BusinessLogicEngine.ChangePartWrapper.ChangePartWrapperSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ChangePartWrapperSoapClient : System.ServiceModel.ClientBase<JGS.BusinessLogicEngine.ChangePartWrapper.ChangePartWrapperSoap>, JGS.BusinessLogicEngine.ChangePartWrapper.ChangePartWrapperSoap {
        
        public ChangePartWrapperSoapClient() {
        }
        
        public ChangePartWrapperSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ChangePartWrapperSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ChangePartWrapperSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ChangePartWrapperSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        JGS.BusinessLogicEngine.ChangePartWrapper.PerformChangePartResponse JGS.BusinessLogicEngine.ChangePartWrapper.ChangePartWrapperSoap.PerformChangePart(JGS.BusinessLogicEngine.ChangePartWrapper.PerformChangePartRequest request) {
            return base.Channel.PerformChangePart(request);
        }
        
        public string PerformChangePart(JGS.BusinessLogicEngine.ChangePartWrapper.ChangePartInfo ChangePartInfo, bool JustReturnXMLString) {
            JGS.BusinessLogicEngine.ChangePartWrapper.PerformChangePartRequest inValue = new JGS.BusinessLogicEngine.ChangePartWrapper.PerformChangePartRequest();
            inValue.Body = new JGS.BusinessLogicEngine.ChangePartWrapper.PerformChangePartRequestBody();
            inValue.Body.ChangePartInfo = ChangePartInfo;
            inValue.Body.JustReturnXMLString = JustReturnXMLString;
            JGS.BusinessLogicEngine.ChangePartWrapper.PerformChangePartResponse retVal = ((JGS.BusinessLogicEngine.ChangePartWrapper.ChangePartWrapperSoap)(this)).PerformChangePart(inValue);
            return retVal.Body.PerformChangePartResult;
        }
    }
}
