//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4963
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JGS.Web.DTVTriggerProviders.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://jgswebservicesstg/JGSPrintService.asmx")]
        public string JGS_Web_DTVTriggerProviders_Printing_JGSPrintService {
            get {
                return ((string)(this["JGS_Web_DTVTriggerProviders_Printing_JGSPrintService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://jgswebservicesstg/QueryAdapterWrapper.asmx")]
        public string JGS_Web_DTVTriggerProviders_QA_QueryAdapterWrapper {
            get {
                return ((string)(this["JGS_Web_DTVTriggerProviders_QA_QueryAdapterWrapper"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://jgswebservicesstg/CamIdValidationService.asmx")]
        public string JGS_Web_DTVTriggerProviders_CamId_CamIdValidationService {
            get {
                return ((string)(this["JGS_Web_DTVTriggerProviders_CamId_CamIdValidationService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://jgswebservicesstg/ChangePartWrapper.asmx")]
        public string JGS_Web_DTVTriggerProviders_ChangePart_ChangePartWrapper {
            get {
                return ((string)(this["JGS_Web_DTVTriggerProviders_ChangePart_ChangePartWrapper"]));
            }
        }
    }
}
