//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMObjects.ReceiptWrapper {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ReceiptWrapper.ReceiptWrapperSoap")]
    public interface ReceiptWrapperSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateCRO", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CreateCRO(CRMObjects.ReceiptWrapper.CROInfo CROInfo, bool JustReturnXML);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateRO_Receipt", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CreateRO_Receipt(CRMObjects.ReceiptWrapper.CROInfo CROInfo, CRMObjects.ReceiptWrapper.ReceiptInfo ReceiptInfo, bool JustReturnXML);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Receipt", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Receipt(CRMObjects.ReceiptWrapper.ReceiptInfo ReceiptInfo, string RefOrder);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateCROV2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CreateCROV2(CRMObjects.ReceiptWrapper.createReferenceOrderInfo createReferenceOrderInfo, bool JustReturnXML);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReceiptV2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ReceiptV2(CRMObjects.ReceiptWrapper.ReceiptInfo ReceiptInfo, string XelusIO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateRO", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string UpdateRO(CRMObjects.ReceiptWrapper.createReferenceOrderInfo updateReferenceOrderInfo, bool JustReturnXML);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateRO_ReceiptV2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CreateRO_ReceiptV2(CRMObjects.ReceiptWrapper.createReferenceOrderInfo createReferenceOrderInfo, CRMObjects.ReceiptWrapper.ReceiptInfo ReceiptInfo, bool JustReturnXML);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Search_RO", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Search_RO(string OrderIdentificatorValue, CRMObjects.ReceiptWrapper.SearchROTypes IdentificatorType, string userName, string DefaultGeo, string RO, string IO, string SN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLineInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetLineInfo(string OrderId, string userName, string P_IO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLineSerialData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetLineSerialData(string OrderId, string LineId, string userName, string P_IO);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CROInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string clientField;
        
        private string contractField;
        
        private string bTTField;
        
        private string orderStatusField;
        
        private string geographyField;
        
        private string warehouseField;
        
        private string customerIDField;
        
        private string customerPOField;
        
        private string clientRef1Field;
        
        private string clientRef2Field;
        
        private string documentNoField;
        
        private string headerNotesField;
        
        private FlexFields[] headerFlexFieldsField;
        
        private CROLine[] linesField;
        
        private string contactNameField;
        
        private string contactTitleField;
        
        private string contactEmailField;
        
        private PhoneTypes[] phoneListField;
        
        private string contactDescripField;
        
        private string contactAddress1Field;
        
        private string contactAddress2Field;
        
        private string contactAddress3Field;
        
        private string contactCityField;
        
        private string contactStateField;
        
        private string contactPostalCodeField;
        
        private string contactCountryField;
        
        private string contactAddressDescripField;
        
        private string userNameField;
        
        private string userPassField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Client {
            get {
                return this.clientField;
            }
            set {
                this.clientField = value;
                this.RaisePropertyChanged("Client");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Contract {
            get {
                return this.contractField;
            }
            set {
                this.contractField = value;
                this.RaisePropertyChanged("Contract");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string BTT {
            get {
                return this.bTTField;
            }
            set {
                this.bTTField = value;
                this.RaisePropertyChanged("BTT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string OrderStatus {
            get {
                return this.orderStatusField;
            }
            set {
                this.orderStatusField = value;
                this.RaisePropertyChanged("OrderStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Geography {
            get {
                return this.geographyField;
            }
            set {
                this.geographyField = value;
                this.RaisePropertyChanged("Geography");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Warehouse {
            get {
                return this.warehouseField;
            }
            set {
                this.warehouseField = value;
                this.RaisePropertyChanged("Warehouse");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string CustomerID {
            get {
                return this.customerIDField;
            }
            set {
                this.customerIDField = value;
                this.RaisePropertyChanged("CustomerID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string CustomerPO {
            get {
                return this.customerPOField;
            }
            set {
                this.customerPOField = value;
                this.RaisePropertyChanged("CustomerPO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string ClientRef1 {
            get {
                return this.clientRef1Field;
            }
            set {
                this.clientRef1Field = value;
                this.RaisePropertyChanged("ClientRef1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string ClientRef2 {
            get {
                return this.clientRef2Field;
            }
            set {
                this.clientRef2Field = value;
                this.RaisePropertyChanged("ClientRef2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string DocumentNo {
            get {
                return this.documentNoField;
            }
            set {
                this.documentNoField = value;
                this.RaisePropertyChanged("DocumentNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string HeaderNotes {
            get {
                return this.headerNotesField;
            }
            set {
                this.headerNotesField = value;
                this.RaisePropertyChanged("HeaderNotes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=12)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public FlexFields[] HeaderFlexFields {
            get {
                return this.headerFlexFieldsField;
            }
            set {
                this.headerFlexFieldsField = value;
                this.RaisePropertyChanged("HeaderFlexFields");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=13)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public CROLine[] Lines {
            get {
                return this.linesField;
            }
            set {
                this.linesField = value;
                this.RaisePropertyChanged("Lines");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string ContactName {
            get {
                return this.contactNameField;
            }
            set {
                this.contactNameField = value;
                this.RaisePropertyChanged("ContactName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string ContactTitle {
            get {
                return this.contactTitleField;
            }
            set {
                this.contactTitleField = value;
                this.RaisePropertyChanged("ContactTitle");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string ContactEmail {
            get {
                return this.contactEmailField;
            }
            set {
                this.contactEmailField = value;
                this.RaisePropertyChanged("ContactEmail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=17)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public PhoneTypes[] PhoneList {
            get {
                return this.phoneListField;
            }
            set {
                this.phoneListField = value;
                this.RaisePropertyChanged("PhoneList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string ContactDescrip {
            get {
                return this.contactDescripField;
            }
            set {
                this.contactDescripField = value;
                this.RaisePropertyChanged("ContactDescrip");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string ContactAddress1 {
            get {
                return this.contactAddress1Field;
            }
            set {
                this.contactAddress1Field = value;
                this.RaisePropertyChanged("ContactAddress1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string ContactAddress2 {
            get {
                return this.contactAddress2Field;
            }
            set {
                this.contactAddress2Field = value;
                this.RaisePropertyChanged("ContactAddress2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string ContactAddress3 {
            get {
                return this.contactAddress3Field;
            }
            set {
                this.contactAddress3Field = value;
                this.RaisePropertyChanged("ContactAddress3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string ContactCity {
            get {
                return this.contactCityField;
            }
            set {
                this.contactCityField = value;
                this.RaisePropertyChanged("ContactCity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string ContactState {
            get {
                return this.contactStateField;
            }
            set {
                this.contactStateField = value;
                this.RaisePropertyChanged("ContactState");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string ContactPostalCode {
            get {
                return this.contactPostalCodeField;
            }
            set {
                this.contactPostalCodeField = value;
                this.RaisePropertyChanged("ContactPostalCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string ContactCountry {
            get {
                return this.contactCountryField;
            }
            set {
                this.contactCountryField = value;
                this.RaisePropertyChanged("ContactCountry");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string ContactAddressDescrip {
            get {
                return this.contactAddressDescripField;
            }
            set {
                this.contactAddressDescripField = value;
                this.RaisePropertyChanged("ContactAddressDescrip");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("UserName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public string UserPass {
            get {
                return this.userPassField;
            }
            set {
                this.userPassField = value;
                this.RaisePropertyChanged("UserPass");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class FlexFields : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class RDEOrderPart : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string bcnField;
        
        private string notesField;
        
        private string orderIdField;
        
        private string orderLineIdField;
        
        private FlexFields[] partFlexFieldsField;
        
        private string reasonCodeNameField;
        
        private string reasonNotesField;
        
        private string serialNoField;
        
        private string shippingTermsField;
        
        private string statusField;
        
        private string taxableIndField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string bcn {
            get {
                return this.bcnField;
            }
            set {
                this.bcnField = value;
                this.RaisePropertyChanged("bcn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string notes {
            get {
                return this.notesField;
            }
            set {
                this.notesField = value;
                this.RaisePropertyChanged("notes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string orderId {
            get {
                return this.orderIdField;
            }
            set {
                this.orderIdField = value;
                this.RaisePropertyChanged("orderId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string orderLineId {
            get {
                return this.orderLineIdField;
            }
            set {
                this.orderLineIdField = value;
                this.RaisePropertyChanged("orderLineId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=4)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public FlexFields[] partFlexFields {
            get {
                return this.partFlexFieldsField;
            }
            set {
                this.partFlexFieldsField = value;
                this.RaisePropertyChanged("partFlexFields");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string reasonCodeName {
            get {
                return this.reasonCodeNameField;
            }
            set {
                this.reasonCodeNameField = value;
                this.RaisePropertyChanged("reasonCodeName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string reasonNotes {
            get {
                return this.reasonNotesField;
            }
            set {
                this.reasonNotesField = value;
                this.RaisePropertyChanged("reasonNotes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string serialNo {
            get {
                return this.serialNoField;
            }
            set {
                this.serialNoField = value;
                this.RaisePropertyChanged("serialNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string ShippingTerms {
            get {
                return this.shippingTermsField;
            }
            set {
                this.shippingTermsField = value;
                this.RaisePropertyChanged("ShippingTerms");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string TaxableInd {
            get {
                return this.taxableIndField;
            }
            set {
                this.taxableIndField = value;
                this.RaisePropertyChanged("TaxableInd");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ReferenceOrderLine : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string aBomPNField;
        
        private string conditionField;
        
        private string currencyField;
        
        private string custOrderLineNoField;
        
        private string custPartNoField;
        
        private FlexFields[] lineFlexFieldsField;
        
        private string manufacturerField;
        
        private string manufacturerPartNoField;
        
        private string notesField;
        
        private string orderLineNoField;
        
        private RDEOrderPart[] partListField;
        
        private string partNoField;
        
        private string priorityField;
        
        private string qtyField;
        
        private string reasonCodeField;
        
        private string reasonNotesField;
        
        private string shippingTermsAbbrField;
        
        private string statusField;
        
        private string taxableFlagField;
        
        private string unitPriceField;
        
        private string warrantyFlagField;
        
        private string ordShipTerm_NameField;
        
        private string ordShipTerm_AllowPartialShipmentField;
        
        private string ordShipTerm_CarrierField;
        
        private string ordShipTerm_CarrierTypeField;
        
        private string ordShipTerm_FobCodeField;
        
        private string ordShipTerm_FreightAccountCodeField;
        
        private string ordShipTerm_ServiceTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ABomPN {
            get {
                return this.aBomPNField;
            }
            set {
                this.aBomPNField = value;
                this.RaisePropertyChanged("ABomPN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string condition {
            get {
                return this.conditionField;
            }
            set {
                this.conditionField = value;
                this.RaisePropertyChanged("condition");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
                this.RaisePropertyChanged("currency");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string custOrderLineNo {
            get {
                return this.custOrderLineNoField;
            }
            set {
                this.custOrderLineNoField = value;
                this.RaisePropertyChanged("custOrderLineNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string custPartNo {
            get {
                return this.custPartNoField;
            }
            set {
                this.custPartNoField = value;
                this.RaisePropertyChanged("custPartNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=5)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public FlexFields[] lineFlexFields {
            get {
                return this.lineFlexFieldsField;
            }
            set {
                this.lineFlexFieldsField = value;
                this.RaisePropertyChanged("lineFlexFields");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string manufacturer {
            get {
                return this.manufacturerField;
            }
            set {
                this.manufacturerField = value;
                this.RaisePropertyChanged("manufacturer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string manufacturerPartNo {
            get {
                return this.manufacturerPartNoField;
            }
            set {
                this.manufacturerPartNoField = value;
                this.RaisePropertyChanged("manufacturerPartNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string notes {
            get {
                return this.notesField;
            }
            set {
                this.notesField = value;
                this.RaisePropertyChanged("notes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string orderLineNo {
            get {
                return this.orderLineNoField;
            }
            set {
                this.orderLineNoField = value;
                this.RaisePropertyChanged("orderLineNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=10)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public RDEOrderPart[] partList {
            get {
                return this.partListField;
            }
            set {
                this.partListField = value;
                this.RaisePropertyChanged("partList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string partNo {
            get {
                return this.partNoField;
            }
            set {
                this.partNoField = value;
                this.RaisePropertyChanged("partNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string priority {
            get {
                return this.priorityField;
            }
            set {
                this.priorityField = value;
                this.RaisePropertyChanged("priority");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string qty {
            get {
                return this.qtyField;
            }
            set {
                this.qtyField = value;
                this.RaisePropertyChanged("qty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string reasonCode {
            get {
                return this.reasonCodeField;
            }
            set {
                this.reasonCodeField = value;
                this.RaisePropertyChanged("reasonCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string reasonNotes {
            get {
                return this.reasonNotesField;
            }
            set {
                this.reasonNotesField = value;
                this.RaisePropertyChanged("reasonNotes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string shippingTermsAbbr {
            get {
                return this.shippingTermsAbbrField;
            }
            set {
                this.shippingTermsAbbrField = value;
                this.RaisePropertyChanged("shippingTermsAbbr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string taxableFlag {
            get {
                return this.taxableFlagField;
            }
            set {
                this.taxableFlagField = value;
                this.RaisePropertyChanged("taxableFlag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string unitPrice {
            get {
                return this.unitPriceField;
            }
            set {
                this.unitPriceField = value;
                this.RaisePropertyChanged("unitPrice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string warrantyFlag {
            get {
                return this.warrantyFlagField;
            }
            set {
                this.warrantyFlagField = value;
                this.RaisePropertyChanged("warrantyFlag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string OrdShipTerm_Name {
            get {
                return this.ordShipTerm_NameField;
            }
            set {
                this.ordShipTerm_NameField = value;
                this.RaisePropertyChanged("OrdShipTerm_Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string OrdShipTerm_AllowPartialShipment {
            get {
                return this.ordShipTerm_AllowPartialShipmentField;
            }
            set {
                this.ordShipTerm_AllowPartialShipmentField = value;
                this.RaisePropertyChanged("OrdShipTerm_AllowPartialShipment");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string OrdShipTerm_Carrier {
            get {
                return this.ordShipTerm_CarrierField;
            }
            set {
                this.ordShipTerm_CarrierField = value;
                this.RaisePropertyChanged("OrdShipTerm_Carrier");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string OrdShipTerm_CarrierType {
            get {
                return this.ordShipTerm_CarrierTypeField;
            }
            set {
                this.ordShipTerm_CarrierTypeField = value;
                this.RaisePropertyChanged("OrdShipTerm_CarrierType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string OrdShipTerm_FobCode {
            get {
                return this.ordShipTerm_FobCodeField;
            }
            set {
                this.ordShipTerm_FobCodeField = value;
                this.RaisePropertyChanged("OrdShipTerm_FobCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string OrdShipTerm_FreightAccountCode {
            get {
                return this.ordShipTerm_FreightAccountCodeField;
            }
            set {
                this.ordShipTerm_FreightAccountCodeField = value;
                this.RaisePropertyChanged("OrdShipTerm_FreightAccountCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public string OrdShipTerm_ServiceType {
            get {
                return this.ordShipTerm_ServiceTypeField;
            }
            set {
                this.ordShipTerm_ServiceTypeField = value;
                this.RaisePropertyChanged("OrdShipTerm_ServiceType");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ContactInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string abbrvField;
        
        private string contactDescField;
        
        private string emailField;
        
        private string faxField;
        
        private string mobilePhoneField;
        
        private string nameField;
        
        private string pagerField;
        
        private string primaryPhoneField;
        
        private string titleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string abbrv {
            get {
                return this.abbrvField;
            }
            set {
                this.abbrvField = value;
                this.RaisePropertyChanged("abbrv");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string contactDesc {
            get {
                return this.contactDescField;
            }
            set {
                this.contactDescField = value;
                this.RaisePropertyChanged("contactDesc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string fax {
            get {
                return this.faxField;
            }
            set {
                this.faxField = value;
                this.RaisePropertyChanged("fax");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string mobilePhone {
            get {
                return this.mobilePhoneField;
            }
            set {
                this.mobilePhoneField = value;
                this.RaisePropertyChanged("mobilePhone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string pager {
            get {
                return this.pagerField;
            }
            set {
                this.pagerField = value;
                this.RaisePropertyChanged("pager");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string primaryPhone {
            get {
                return this.primaryPhoneField;
            }
            set {
                this.primaryPhoneField = value;
                this.RaisePropertyChanged("primaryPhone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("title");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AddressInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string abbrvField;
        
        private string addrNameField;
        
        private string cityField;
        
        private string countryField;
        
        private string line1Field;
        
        private string line2Field;
        
        private string line3Field;
        
        private string line4Field;
        
        private string postalCodeField;
        
        private string stateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string abbrv {
            get {
                return this.abbrvField;
            }
            set {
                this.abbrvField = value;
                this.RaisePropertyChanged("abbrv");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string addrName {
            get {
                return this.addrNameField;
            }
            set {
                this.addrNameField = value;
                this.RaisePropertyChanged("addrName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string city {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("city");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
                this.RaisePropertyChanged("country");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string line1 {
            get {
                return this.line1Field;
            }
            set {
                this.line1Field = value;
                this.RaisePropertyChanged("line1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string line2 {
            get {
                return this.line2Field;
            }
            set {
                this.line2Field = value;
                this.RaisePropertyChanged("line2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string line3 {
            get {
                return this.line3Field;
            }
            set {
                this.line3Field = value;
                this.RaisePropertyChanged("line3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string line4 {
            get {
                return this.line4Field;
            }
            set {
                this.line4Field = value;
                this.RaisePropertyChanged("line4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string postalCode {
            get {
                return this.postalCodeField;
            }
            set {
                this.postalCodeField = value;
                this.RaisePropertyChanged("postalCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string state {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
                this.RaisePropertyChanged("state");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ContactAddressInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private AddressInfo addressInfoField;
        
        private ContactInfo contactInfoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public AddressInfo AddressInfo {
            get {
                return this.addressInfoField;
            }
            set {
                this.addressInfoField = value;
                this.RaisePropertyChanged("AddressInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ContactInfo ContactInfo {
            get {
                return this.contactInfoField;
            }
            set {
                this.contactInfoField = value;
                this.RaisePropertyChanged("ContactInfo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ReferenceOrderInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ContactAddressInfo billToDoField;
        
        private string billingTermsAbbrField;
        
        private string btTypeField;
        
        private string clientAbbrField;
        
        private string clientRefNo1Field;
        
        private string clientRefNo2Field;
        
        private string contractField;
        
        private string custOrderNoField;
        
        private string customerAbbrField;
        
        private string dfltPOAbbrvField;
        
        private string dfltPaymentTermsAbbrvField;
        
        private string documentNoField;
        
        private string geographyField;
        
        private FlexFields[] headerFlexFieldsField;
        
        private string idField;
        
        private string inboundAddressAbbrField;
        
        private ReferenceOrderLine[] newLineListField;
        
        private string notesField;
        
        private string outboundAddressAbbrField;
        
        private ContactAddressInfo shipToDoField;
        
        private string statusField;
        
        private string systemIdField;
        
        private string warehouseField;
        
        private FlexFields[] wsFlexFieldsField;
        
        private string ordTradPart_NameField;
        
        private string ordTradPart_NoteField;
        
        private string ordTradPart_OrderPaymentTermsField;
        
        private string ordTradPart_BillShipToSameContactAndAddressField;
        
        private string nonValidatedTradingPartnerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ContactAddressInfo billToDo {
            get {
                return this.billToDoField;
            }
            set {
                this.billToDoField = value;
                this.RaisePropertyChanged("billToDo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string billingTermsAbbr {
            get {
                return this.billingTermsAbbrField;
            }
            set {
                this.billingTermsAbbrField = value;
                this.RaisePropertyChanged("billingTermsAbbr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string btType {
            get {
                return this.btTypeField;
            }
            set {
                this.btTypeField = value;
                this.RaisePropertyChanged("btType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string clientAbbr {
            get {
                return this.clientAbbrField;
            }
            set {
                this.clientAbbrField = value;
                this.RaisePropertyChanged("clientAbbr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string clientRefNo1 {
            get {
                return this.clientRefNo1Field;
            }
            set {
                this.clientRefNo1Field = value;
                this.RaisePropertyChanged("clientRefNo1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string clientRefNo2 {
            get {
                return this.clientRefNo2Field;
            }
            set {
                this.clientRefNo2Field = value;
                this.RaisePropertyChanged("clientRefNo2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string contract {
            get {
                return this.contractField;
            }
            set {
                this.contractField = value;
                this.RaisePropertyChanged("contract");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string custOrderNo {
            get {
                return this.custOrderNoField;
            }
            set {
                this.custOrderNoField = value;
                this.RaisePropertyChanged("custOrderNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string customerAbbr {
            get {
                return this.customerAbbrField;
            }
            set {
                this.customerAbbrField = value;
                this.RaisePropertyChanged("customerAbbr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string dfltPOAbbrv {
            get {
                return this.dfltPOAbbrvField;
            }
            set {
                this.dfltPOAbbrvField = value;
                this.RaisePropertyChanged("dfltPOAbbrv");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string dfltPaymentTermsAbbrv {
            get {
                return this.dfltPaymentTermsAbbrvField;
            }
            set {
                this.dfltPaymentTermsAbbrvField = value;
                this.RaisePropertyChanged("dfltPaymentTermsAbbrv");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string documentNo {
            get {
                return this.documentNoField;
            }
            set {
                this.documentNoField = value;
                this.RaisePropertyChanged("documentNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string geography {
            get {
                return this.geographyField;
            }
            set {
                this.geographyField = value;
                this.RaisePropertyChanged("geography");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=13)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public FlexFields[] headerFlexFields {
            get {
                return this.headerFlexFieldsField;
            }
            set {
                this.headerFlexFieldsField = value;
                this.RaisePropertyChanged("headerFlexFields");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string inboundAddressAbbr {
            get {
                return this.inboundAddressAbbrField;
            }
            set {
                this.inboundAddressAbbrField = value;
                this.RaisePropertyChanged("inboundAddressAbbr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=16)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ReferenceOrderLine[] newLineList {
            get {
                return this.newLineListField;
            }
            set {
                this.newLineListField = value;
                this.RaisePropertyChanged("newLineList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string notes {
            get {
                return this.notesField;
            }
            set {
                this.notesField = value;
                this.RaisePropertyChanged("notes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string outboundAddressAbbr {
            get {
                return this.outboundAddressAbbrField;
            }
            set {
                this.outboundAddressAbbrField = value;
                this.RaisePropertyChanged("outboundAddressAbbr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public ContactAddressInfo shipToDo {
            get {
                return this.shipToDoField;
            }
            set {
                this.shipToDoField = value;
                this.RaisePropertyChanged("shipToDo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string systemId {
            get {
                return this.systemIdField;
            }
            set {
                this.systemIdField = value;
                this.RaisePropertyChanged("systemId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string warehouse {
            get {
                return this.warehouseField;
            }
            set {
                this.warehouseField = value;
                this.RaisePropertyChanged("warehouse");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=23)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public FlexFields[] wsFlexFields {
            get {
                return this.wsFlexFieldsField;
            }
            set {
                this.wsFlexFieldsField = value;
                this.RaisePropertyChanged("wsFlexFields");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string OrdTradPart_Name {
            get {
                return this.ordTradPart_NameField;
            }
            set {
                this.ordTradPart_NameField = value;
                this.RaisePropertyChanged("OrdTradPart_Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string OrdTradPart_Note {
            get {
                return this.ordTradPart_NoteField;
            }
            set {
                this.ordTradPart_NoteField = value;
                this.RaisePropertyChanged("OrdTradPart_Note");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string OrdTradPart_OrderPaymentTerms {
            get {
                return this.ordTradPart_OrderPaymentTermsField;
            }
            set {
                this.ordTradPart_OrderPaymentTermsField = value;
                this.RaisePropertyChanged("OrdTradPart_OrderPaymentTerms");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public string OrdTradPart_BillShipToSameContactAndAddress {
            get {
                return this.ordTradPart_BillShipToSameContactAndAddressField;
            }
            set {
                this.ordTradPart_BillShipToSameContactAndAddressField = value;
                this.RaisePropertyChanged("OrdTradPart_BillShipToSameContactAndAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public string NonValidatedTradingPartner {
            get {
                return this.nonValidatedTradingPartnerField;
            }
            set {
                this.nonValidatedTradingPartnerField = value;
                this.RaisePropertyChanged("NonValidatedTradingPartner");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class createReferenceOrderInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string systemIdField;
        
        private string userNameField;
        
        private string passwordField;
        
        private ReferenceOrderInfo orderInfoField;
        
        private string ipField;
        
        private string callSourceField;
        
        private string aPIUsage_LocationNameField;
        
        private string aPIUsage_ClientNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string systemId {
            get {
                return this.systemIdField;
            }
            set {
                this.systemIdField = value;
                this.RaisePropertyChanged("systemId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("UserName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public ReferenceOrderInfo OrderInfo {
            get {
                return this.orderInfoField;
            }
            set {
                this.orderInfoField = value;
                this.RaisePropertyChanged("OrderInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string IP {
            get {
                return this.ipField;
            }
            set {
                this.ipField = value;
                this.RaisePropertyChanged("IP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string CallSource {
            get {
                return this.callSourceField;
            }
            set {
                this.callSourceField = value;
                this.RaisePropertyChanged("CallSource");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string APIUsage_LocationName {
            get {
                return this.aPIUsage_LocationNameField;
            }
            set {
                this.aPIUsage_LocationNameField = value;
                this.RaisePropertyChanged("APIUsage_LocationName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string APIUsage_ClientName {
            get {
                return this.aPIUsage_ClientNameField;
            }
            set {
                this.aPIUsage_ClientNameField = value;
                this.RaisePropertyChanged("APIUsage_ClientName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ExternalReceiptData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string receiptNumberField;
        
        private string applicationField;
        
        private string warehouseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ReceiptNumber {
            get {
                return this.receiptNumberField;
            }
            set {
                this.receiptNumberField = value;
                this.RaisePropertyChanged("ReceiptNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Application {
            get {
                return this.applicationField;
            }
            set {
                this.applicationField = value;
                this.RaisePropertyChanged("Application");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Warehouse {
            get {
                return this.warehouseField;
            }
            set {
                this.warehouseField = value;
                this.RaisePropertyChanged("Warehouse");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Item : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fixedAssetTagField;
        
        private string noteField;
        
        private string partNumberField;
        
        private int quantityField;
        
        private string reasonCodeField;
        
        private string reasonNotesField;
        
        private string resultCodeField;
        
        private string revisionLevelField;
        
        private string bCNField;
        
        private string serialNumberField;
        
        private FlexFields[] itemFlexFieldsField;
        
        private bool warrantyField;
        
        private string originalSerialNumberField;
        
        private string originalBCNField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string FixedAssetTag {
            get {
                return this.fixedAssetTagField;
            }
            set {
                this.fixedAssetTagField = value;
                this.RaisePropertyChanged("FixedAssetTag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Note {
            get {
                return this.noteField;
            }
            set {
                this.noteField = value;
                this.RaisePropertyChanged("Note");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string PartNumber {
            get {
                return this.partNumberField;
            }
            set {
                this.partNumberField = value;
                this.RaisePropertyChanged("PartNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
                this.RaisePropertyChanged("Quantity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ReasonCode {
            get {
                return this.reasonCodeField;
            }
            set {
                this.reasonCodeField = value;
                this.RaisePropertyChanged("ReasonCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ReasonNotes {
            get {
                return this.reasonNotesField;
            }
            set {
                this.reasonNotesField = value;
                this.RaisePropertyChanged("ReasonNotes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string ResultCode {
            get {
                return this.resultCodeField;
            }
            set {
                this.resultCodeField = value;
                this.RaisePropertyChanged("ResultCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string RevisionLevel {
            get {
                return this.revisionLevelField;
            }
            set {
                this.revisionLevelField = value;
                this.RaisePropertyChanged("RevisionLevel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string BCN {
            get {
                return this.bCNField;
            }
            set {
                this.bCNField = value;
                this.RaisePropertyChanged("BCN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string SerialNumber {
            get {
                return this.serialNumberField;
            }
            set {
                this.serialNumberField = value;
                this.RaisePropertyChanged("SerialNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=10)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public FlexFields[] ItemFlexFields {
            get {
                return this.itemFlexFieldsField;
            }
            set {
                this.itemFlexFieldsField = value;
                this.RaisePropertyChanged("ItemFlexFields");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public bool Warranty {
            get {
                return this.warrantyField;
            }
            set {
                this.warrantyField = value;
                this.RaisePropertyChanged("Warranty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string OriginalSerialNumber {
            get {
                return this.originalSerialNumberField;
            }
            set {
                this.originalSerialNumberField = value;
                this.RaisePropertyChanged("OriginalSerialNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string OriginalBCN {
            get {
                return this.originalBCNField;
            }
            set {
                this.originalBCNField = value;
                this.RaisePropertyChanged("OriginalBCN");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Line : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Item[] itemField;
        
        private FlexFields[] lineFlexFieldsField;
        
        private string lineNoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Item[] Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("Item");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public FlexFields[] LineFlexFields {
            get {
                return this.lineFlexFieldsField;
            }
            set {
                this.lineFlexFieldsField = value;
                this.RaisePropertyChanged("LineFlexFields");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string LineNo {
            get {
                return this.lineNoField;
            }
            set {
                this.lineNoField = value;
                this.RaisePropertyChanged("LineNo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ReceiptInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string userField;
        
        private string pwdField;
        
        private string carrierNameField;
        
        private string packingListNoField;
        
        private string noteField;
        
        private string trackingNoField;
        
        private Line[] linesField;
        
        private FlexFields[] receiptFlexFieldsField;
        
        private ExternalReceiptData externalReceiptDataField;
        
        private string ipField;
        
        private string callSourceField;
        
        private string aPIUsage_LocationNameField;
        
        private string aPIUsage_ClientNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string User {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
                this.RaisePropertyChanged("User");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Pwd {
            get {
                return this.pwdField;
            }
            set {
                this.pwdField = value;
                this.RaisePropertyChanged("Pwd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string CarrierName {
            get {
                return this.carrierNameField;
            }
            set {
                this.carrierNameField = value;
                this.RaisePropertyChanged("CarrierName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string PackingListNo {
            get {
                return this.packingListNoField;
            }
            set {
                this.packingListNoField = value;
                this.RaisePropertyChanged("PackingListNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Note {
            get {
                return this.noteField;
            }
            set {
                this.noteField = value;
                this.RaisePropertyChanged("Note");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string TrackingNo {
            get {
                return this.trackingNoField;
            }
            set {
                this.trackingNoField = value;
                this.RaisePropertyChanged("TrackingNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=6)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Line[] Lines {
            get {
                return this.linesField;
            }
            set {
                this.linesField = value;
                this.RaisePropertyChanged("Lines");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=7)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public FlexFields[] ReceiptFlexFields {
            get {
                return this.receiptFlexFieldsField;
            }
            set {
                this.receiptFlexFieldsField = value;
                this.RaisePropertyChanged("ReceiptFlexFields");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public ExternalReceiptData ExternalReceiptData {
            get {
                return this.externalReceiptDataField;
            }
            set {
                this.externalReceiptDataField = value;
                this.RaisePropertyChanged("ExternalReceiptData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string IP {
            get {
                return this.ipField;
            }
            set {
                this.ipField = value;
                this.RaisePropertyChanged("IP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string CallSource {
            get {
                return this.callSourceField;
            }
            set {
                this.callSourceField = value;
                this.RaisePropertyChanged("CallSource");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string APIUsage_LocationName {
            get {
                return this.aPIUsage_LocationNameField;
            }
            set {
                this.aPIUsage_LocationNameField = value;
                this.RaisePropertyChanged("APIUsage_LocationName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string APIUsage_ClientName {
            get {
                return this.aPIUsage_ClientNameField;
            }
            set {
                this.aPIUsage_ClientNameField = value;
                this.RaisePropertyChanged("APIUsage_ClientName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PhoneTypes : object, System.ComponentModel.INotifyPropertyChanged {
        
        private PhoneTypesList typeField;
        
        private string numberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public PhoneTypesList Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
                this.RaisePropertyChanged("Number");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum PhoneTypesList {
        
        /// <remarks/>
        DaytimePhone,
        
        /// <remarks/>
        EveningPhone,
        
        /// <remarks/>
        MobilePhone,
        
        /// <remarks/>
        Pager,
        
        /// <remarks/>
        Fax,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CROSerialNumbers : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string serialNumberField;
        
        private FlexFields[] serialFlexFieldsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string SerialNumber {
            get {
                return this.serialNumberField;
            }
            set {
                this.serialNumberField = value;
                this.RaisePropertyChanged("SerialNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public FlexFields[] SerialFlexFields {
            get {
                return this.serialFlexFieldsField;
            }
            set {
                this.serialFlexFieldsField = value;
                this.RaisePropertyChanged("SerialFlexFields");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CROLine : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string partNumberField;
        
        private string quantityField;
        
        private string unitPriceField;
        
        private string currencyField;
        
        private string warrantyField;
        
        private string taxableField;
        
        private string priorityField;
        
        private string conditionField;
        
        private string customerPoLineNoField;
        
        private string linesNotesField;
        
        private FlexFields[] lineFlexFieldsField;
        
        private CROSerialNumbers[] serialNumbersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string PartNumber {
            get {
                return this.partNumberField;
            }
            set {
                this.partNumberField = value;
                this.RaisePropertyChanged("PartNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
                this.RaisePropertyChanged("Quantity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string UnitPrice {
            get {
                return this.unitPriceField;
            }
            set {
                this.unitPriceField = value;
                this.RaisePropertyChanged("UnitPrice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
                this.RaisePropertyChanged("Currency");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Warranty {
            get {
                return this.warrantyField;
            }
            set {
                this.warrantyField = value;
                this.RaisePropertyChanged("Warranty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Taxable {
            get {
                return this.taxableField;
            }
            set {
                this.taxableField = value;
                this.RaisePropertyChanged("Taxable");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Priority {
            get {
                return this.priorityField;
            }
            set {
                this.priorityField = value;
                this.RaisePropertyChanged("Priority");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Condition {
            get {
                return this.conditionField;
            }
            set {
                this.conditionField = value;
                this.RaisePropertyChanged("Condition");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string CustomerPoLineNo {
            get {
                return this.customerPoLineNoField;
            }
            set {
                this.customerPoLineNoField = value;
                this.RaisePropertyChanged("CustomerPoLineNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string LinesNotes {
            get {
                return this.linesNotesField;
            }
            set {
                this.linesNotesField = value;
                this.RaisePropertyChanged("LinesNotes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=10)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public FlexFields[] LineFlexFields {
            get {
                return this.lineFlexFieldsField;
            }
            set {
                this.lineFlexFieldsField = value;
                this.RaisePropertyChanged("LineFlexFields");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=11)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public CROSerialNumbers[] SerialNumbers {
            get {
                return this.serialNumbersField;
            }
            set {
                this.serialNumbersField = value;
                this.RaisePropertyChanged("SerialNumbers");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum SearchROTypes {
        
        /// <remarks/>
        ReferenceOrderID,
        
        /// <remarks/>
        ClientReferenceNo1,
        
        /// <remarks/>
        ClientReferenceNo2,
        
        /// <remarks/>
        InboundOrderID,
        
        /// <remarks/>
        SerialNumber,
        
        /// <remarks/>
        PartNumber,
        
        /// <remarks/>
        TrackingNo,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ReceiptWrapperSoapChannel : CRMObjects.ReceiptWrapper.ReceiptWrapperSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReceiptWrapperSoapClient : System.ServiceModel.ClientBase<CRMObjects.ReceiptWrapper.ReceiptWrapperSoap>, CRMObjects.ReceiptWrapper.ReceiptWrapperSoap {
        
        public ReceiptWrapperSoapClient() {
        }
        
        public ReceiptWrapperSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReceiptWrapperSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReceiptWrapperSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReceiptWrapperSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string CreateCRO(CRMObjects.ReceiptWrapper.CROInfo CROInfo, bool JustReturnXML) {
            return base.Channel.CreateCRO(CROInfo, JustReturnXML);
        }
        
        public string CreateRO_Receipt(CRMObjects.ReceiptWrapper.CROInfo CROInfo, CRMObjects.ReceiptWrapper.ReceiptInfo ReceiptInfo, bool JustReturnXML) {
            return base.Channel.CreateRO_Receipt(CROInfo, ReceiptInfo, JustReturnXML);
        }
        
        public string Receipt(CRMObjects.ReceiptWrapper.ReceiptInfo ReceiptInfo, string RefOrder) {
            return base.Channel.Receipt(ReceiptInfo, RefOrder);
        }
        
        public string CreateCROV2(CRMObjects.ReceiptWrapper.createReferenceOrderInfo createReferenceOrderInfo, bool JustReturnXML) {
            return base.Channel.CreateCROV2(createReferenceOrderInfo, JustReturnXML);
        }
        
        public string ReceiptV2(CRMObjects.ReceiptWrapper.ReceiptInfo ReceiptInfo, string XelusIO) {
            return base.Channel.ReceiptV2(ReceiptInfo, XelusIO);
        }
        
        public string UpdateRO(CRMObjects.ReceiptWrapper.createReferenceOrderInfo updateReferenceOrderInfo, bool JustReturnXML) {
            return base.Channel.UpdateRO(updateReferenceOrderInfo, JustReturnXML);
        }
        
        public string CreateRO_ReceiptV2(CRMObjects.ReceiptWrapper.createReferenceOrderInfo createReferenceOrderInfo, CRMObjects.ReceiptWrapper.ReceiptInfo ReceiptInfo, bool JustReturnXML) {
            return base.Channel.CreateRO_ReceiptV2(createReferenceOrderInfo, ReceiptInfo, JustReturnXML);
        }
        
        public System.Data.DataSet Search_RO(string OrderIdentificatorValue, CRMObjects.ReceiptWrapper.SearchROTypes IdentificatorType, string userName, string DefaultGeo, string RO, string IO, string SN) {
            return base.Channel.Search_RO(OrderIdentificatorValue, IdentificatorType, userName, DefaultGeo, RO, IO, SN);
        }
        
        public System.Data.DataSet GetLineInfo(string OrderId, string userName, string P_IO) {
            return base.Channel.GetLineInfo(OrderId, userName, P_IO);
        }
        
        public System.Data.DataSet GetLineSerialData(string OrderId, string LineId, string userName, string P_IO) {
            return base.Channel.GetLineSerialData(OrderId, LineId, userName, P_IO);
        }
    }
}
